language: python
python:
  - 3.8

jobs:
  include:
    - os: windows
      language: shell
      env:
        - BUILD_LANG=NO
        - PATH="/c/Python38:/c/Python38/Scripts:/c/Program Files/nodejs:$PATH"
        - ISO=$ISO_NO
      before_install:
        - deployment/windows_dependencies.cmd
        - wget -O ~/mullebil.iso $ISO
        - powershell -ExecutionPolicy bypass deployment/mount.ps1

    - os: windows
      language: shell
      env:
        - BUILD_LANG=SE
        - PATH="/c/Python38:/c/Python38/Scripts:/c/Program Files/nodejs:$PATH"
        - ISO=$ISO_SE
      before_install:
        - wget -O ~/mullebil.iso $ISO
        - powershell -ExecutionPolicy bypass deployment/mount.ps1

    - os: linux
      env:
        - BUILD_LANG=NO

    - os: linux
      env:
        - BUILD_LANG=SE

  allow_failures:
    - os: windows

addons:
  apt:
    packages:
      - nodejs
      - npm
      - ffmpeg
      - optipng
  ssh_known_hosts: dedicated.datagutten.net

before_install:
  - deployment/imagemagick.sh
  - export PATH="$PWD/bin:$PATH"
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deployment/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - scp -q mulle@dedicated.datagutten.net:/home/mulle/iso/mullebil_$BUILD_LANG.iso ~/mullebil.iso
  - mkdir ~/mullebil
  - sudo mount -o loop ~/mullebil.iso ~/mullebil

install:
  - python -m pip install -r requirements.txt
  - npm install
  - python extract.py ~/mullebil

script:
  - npx gulp build-prod
  - python assets.py 7
  - python build_scripts/topography.py
  - python build_scripts/copy_ui.py

before_deploy:
- deployment/package.sh

deploy:
  provider: script
  skip_cleanup: true
  script: deployment/deploy.sh
  on:
    branch: travis
