language: python
python:
  - 3.8
jobs:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install nodejs --version 10.21.0
        - choco install imagemagick.tool
        - choco install python --version 3.8
        - choco install optipng
      before_script:
        - wget -O ~/mullebil.iso $ISO
        - powershell -ExecutionPolicy bypass deployment/mount.ps1
      env:
        - ISO=$ISO_SE BUILD_LANG=SE
        - PATH="/c/Python38:/c/Python38/Scripts:/c/Program Files/nodejs:$PATH"
    - os: linux
      before_script:
        - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deployment/deploy_rsa.enc -out /tmp/deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
        - scp -q mulle@dedicated.datagutten.net:/home/mulle/iso/mullebil_$BUILD_LANG.iso ~/mullebil.iso
        - mkdir ~/mullebil
        - sudo mount -o loop ~/mullebil.iso ~/mullebil
      env:
        - ISO=$ISO_NO BUILD_LANG=NO
        - ISO=$ISO_SE BUILD_LANG=SE

  allow_failures:
    - os: windows

addons:
  apt:
    packages:
      - nodejs
      - npm
      - ffmpeg
      - optipng
  ssh_known_hosts: dedicated.datagutten.net

before_install:
  - mkdir bin
  - wget -O bin/magick https://imagemagick.org/download/binaries/magick
  - chmod +x bin/magick
  - export PATH="$PWD/bin:$PATH"
  - magick -version

install:
  - python -m pip install -r requirements.txt
  - npm install

script:
  - echo "travis_fold:start:SCRIPT folding starts"
  - python extract.py
  - echo "travis_fold:end:SCRIPT folding ends"
  - npx gulp build-prod
  - python assets.py 7
  - python build_scripts/topography.py
  - python build_scripts/copy_ui.py

before_deploy:
- deployment/package.sh

deploy:
  provider: script
  skip_cleanup: true
  script: deployment/deploy.sh
  on:
    branch: travis
