language: python
python:
  - 3.8

env:
  matrix:
  - ISO=$ISO_NO LANG=NO
  - ISO=$ISO_SE LANG=SE
  global:
    secure: mc3//Nt/1aRwofdnF4bFcG8UQ7EJelaFwiPY5syuOtS909czX4GNR7yHEK3a9wzawD8NWpM8wlkB+1y5MgMsxw/skhdPXzRUM/08bJLePYS3nVs2z4m6cSN03ReOHonkMFwkNvpdUkytlMqv0ndWRXUGwm60VrWD9NuUOullIAMFwcy9hpX44rRBLnRMah5BccGWyw7sDVVPvAqZ+uerFawvGyEn6uLz4v4xJj3LW9r96aTMFcl7aW1rETsDmWA2eJlkWyNpcmmGf+gZuMv0J5WmSTjYQ91GCdcgi++0/0Ic4nEMbP0D2p6tI0tuxM5Jbsdf8UiN4HMElHLBB763Ow95QBlqAV7OpyPO+ZNKQ/4qkbETma+wjml9LT94aUhJI4VPD+xeKJFdVhFCijTgPardiuEAhC2yRAE0QMusTNbacmbmgA6S9rKiH4cVb1bmFbWwyze4wH41DK0x/Si0OVTk4jT7bWlfl5wsb35eGfSb3UNOv4swIFzqqvPbJe1VHmr1wtAKUQMowrd1Fea9z5MT/111wF87H6EavsX60GOGZTTi3fZ707cxFEyox+RELInUrec15D7emX/eV5hkAGHJhcjjJb6aotgkPq8BeNMgCWKyD+8WgOAVDTzyYmlRe38l/djSrMxuWnNQWyToEbgzX8k1U+rMDIw06rk4jEQ=
addons:
  apt:
    packages:
      - nodejs
      - npm
      - ffmpeg
      - sshpass

before_install:
  - mkdir bin
  - wget -O bin/magick https://imagemagick.org/download/binaries/magick
  - chmod +x bin/magick
  - export PATH="$PWD/bin:$PATH"
  - magick -version

install:
  - pip install -r requirements.txt
  - npm install

before_script:
  - wget -O mullebil.iso $ISO
  - mkdir ~/mullebil
  - sudo mount -o loop mullebil.iso ~/mullebil

script:
  - echo "travis_fold:start:SCRIPT folding starts"
  - ./extract.sh
  - echo "travis_fold:end:SCRIPT folding ends"
  - npm run build
after_script:
  - tar -cvzf ~/Mulle_$LANG.tgz .
  - sshpass -e scp mulle@dedicated.datagutten.net:/home/mulle ~/Mulle_$LANG.tgz
