dist: bionic
language: python
python:
  - 3.8

jobs:
  include:
    - os: windows
      language: shell
      env:
        - BUILD_LANG=NO
        - ISO=$ISO_NO
      before_install:
        - deployment/windows_dependencies.cmd
        - export PATH="/c/Python38:/c/Python38/Scripts:/c/Program Files/nodejs:/c/Program Files/ImageMagick-7.0.10-Q16:$PWD/bin:/c/ProgramData/chocolatey/lib/ffmpeg/tools:c/ProgramData/chocolatey/lib/OptiPNG/tools:$PATH"
        - wget -O ~/mullebil.iso $ISO
        - powershell -ExecutionPolicy bypass deployment/mount.ps1
      before_script:
        python build_scripts/rename.py cst_out_new

    - os: windows
      language: shell
      env:
        - BUILD_LANG=SE
        - ISO=$ISO_SE
      before_install:
        - deployment/windows_dependencies.cmd
        - export PATH="/c/Python38:/c/Python38/Scripts:/c/Program Files/nodejs:/c/Program Files/ImageMagick-7.0.10-Q16:$PWD/bin:/c/ProgramData/chocolatey/lib/ffmpeg/tools:c/ProgramData/chocolatey/lib/OptiPNG/tools:$PATH"

    - os: linux
      env:
        - BUILD_LANG=NO
      before_script:
        python build_scripts/rename.py cst_out_new
      deploy:
        provider: script
        skip_cleanup: true
        script: deployment/deploy.sh

    - os: linux
      env:
        - BUILD_LANG=SE
      deploy:
        provider: script
        skip_cleanup: true
        script: deployment/deploy.sh

  allow_failures:
    - os: windows

addons:
  apt:
    packages:
      - ffmpeg
      - optipng
  ssh_known_hosts: dedicated.datagutten.net

before_install:
  - deployment/imagemagick.sh
  - export PATH="$PWD/bin:$PATH"
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deployment/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - scp -q mulle@dedicated.datagutten.net:/home/mulle/iso/mullebil_$BUILD_LANG.iso ~/mullebil.iso
  - nvm install 10

install:
  - python build_scripts/extract_iso.py ~/mullebil.iso
  - python -m pip install -r requirements.txt
  - npm install
  - python extract.py ~/mullebil

script:
  - npx gulp build-full

before_deploy:
- deployment/package.sh
